name: PHP Unit

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [php7.4, php8.0]

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: ${{ matrix.php }} `which composer` install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      env:
        LANG: "en_NZ.UTF-8"
        LANGUAGE: "en_NZ:en"
        LC_ALL: "en_NZ.UTF-8"
      run: ${{ matrix.php }} ./vendor/bin/phpunit
